# Manual pull replication policy
name: "manual-pull-from-dockerhub"
description: "Manually pull specific nginx images from Docker Hub"
replication_mode: "pull"
target_registry: "dockerhub"
trigger_mode: "manual"
bandwidth_limit: "-1"  # Unlimited
override: false
replicate_deletion: false
enabled: true
copy_by_chunk: false

replication_filter:
  - type: "resource"
    value: "image"
  
  - type: "name"
    value: "nginx"
  
  - type: "tag"
    decoration: "matches"
    value: "1.*"
  
  - type: "label"
    decoration: "matches"
    value: "maintainer=NGINX Docker Maintainers"