.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-jobservice-schedules-resume-all - Resume all schedules


.SH SYNOPSIS
\fBharbor jobservice schedules resume-all [flags]\fP


.SH DESCRIPTION
Resume the global scheduler and all schedules.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for resume-all


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
harbor jobservice schedules resume-all
.EE


.SH SEE ALSO
\fBharbor-jobservice-schedules(1)\fP