.nh
.TH "HARBOR" "1"  "Habor Community" "Harbor User Mannuals"

.SH NAME
harbor-tag-immutable-delete - delete immutable rule


.SH SYNOPSIS
\fBharbor tag immutable delete [flags]\fP


.SH DESCRIPTION
delete immutable rule


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-tag-immutable(1)\fP