.nh
.TH "HARBOR" "1"  "Habor Community" "Harbor User Mannuals"

.SH NAME
harbor-info - Display detailed Harbor system, statistics, and CLI environment information


.SH SYNOPSIS
\fBharbor info [flags]\fP


.SH DESCRIPTION
The 'info' command retrieves and displays general information about the Harbor instance,
including system metadata, storage statistics, and CLI environment details such as user identity,
registry address, and CLI version.

.PP
The output can be formatted as table (default), JSON, or YAML using the '--output-format' flag.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for info


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  harbor info
  harbor info --output-format json
  harbor info -o yaml
.EE


.SH SEE ALSO
\fBharbor(1)\fP