.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-project-create - create project


.SH SYNOPSIS
\fBharbor project create [project name] [flags]\fP


.SH DESCRIPTION
create project


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--proxy-cache\fP[=false]
	Whether the project is a proxy cache project

.PP
\fB--public\fP[=false]
	Project is public or private

.PP
\fB--registry-id\fP=""
	ID of referenced registry when creating the proxy cache project

.PP
\fB--storage-limit\fP="-1"
	Storage quota of the project


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-project(1)\fP