.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-tag-retention-create - Create a tag retention rule in a project


.SH SYNOPSIS
\fBharbor tag retention create [flags]\fP


.SH DESCRIPTION
Create a tag retention rule for a project in Harbor to manage the lifecycle of image tags.

.PP
Tag retention rules help users automatically retain or delete specific tags based on
defined criteria, reducing storage usage and improving repository maintenance.

.PP
A user can create up to 15 tag retention rules per project.


.SH OPTIONS
\fB--action\fP="retain"
	Action to perform: 'retain' or 'delete'

.PP
\fB--algorithm\fP="or"
	Rule combination method: 'or' or 'and'

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--level\fP="project"
	Scope of the retention policy: 'project' or 'repository'

.PP
\fB-i\fP, \fB--project-id\fP=-1
	Project ID

.PP
\fB-p\fP, \fB--project-name\fP=""
	Project name

.PP
\fB--repodecoration\fP=""
	Apply or exclude repositories from the rule

.PP
\fB--repolist\fP=""
	Comma-separated list of repositories to apply/exclude

.PP
\fB--tagdecoration\fP=""
	Apply or exclude specific tags from the rule

.PP
\fB--taglist\fP=""
	Comma-separated list of tags to apply/exclude


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  # Retain tags matching 'release-*' at the project level
  harbor tag retention create --level project --action retain --taglist release-*

  # Delete untagged images at the repository level
  harbor retention create --level repository --action delete --tagdecoration untagged
.EE


.SH SEE ALSO
\fBharbor-tag-retention(1)\fP