.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-project-preheat-policy-view - View details of a preheat policy


.SH SYNOPSIS
\fBharbor project preheat policy view [NAME|ID] [POLICY_NAME] [flags]\fP


.SH DESCRIPTION
Get details of a specific P2P preheat policy under a project


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for view

.PP
\fB--id\fP[=false]
	Get preheat policy by project id


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-project-preheat-policy(1)\fP