.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-project-robot - Manage robot accounts


.SH SYNOPSIS
\fBharbor project robot [flags]\fP


.SH DESCRIPTION
Manage robot accounts


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for robot


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  harbor project robot list
.EE


.SH SEE ALSO
\fBharbor-project(1)\fP, \fBharbor-project-robot-create(1)\fP, \fBharbor-project-robot-delete(1)\fP, \fBharbor-project-robot-list(1)\fP, \fBharbor-project-robot-refresh(1)\fP, \fBharbor-project-robot-update(1)\fP, \fBharbor-project-robot-view(1)\fP