.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-quota-view - get quota by quota ID


.SH SYNOPSIS
\fBharbor quota view [quotaID] [flags]\fP


.SH DESCRIPTION
get quota by quota ID


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for view

.PP
\fB--project-id\fP=""
	Get quota by project ID

.PP
\fB--project-name\fP=""
	Get quota by project-name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-quota(1)\fP