.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-usergroup-update - update user group


.SH SYNOPSIS
\fBharbor usergroup update [flags]\fP


.SH DESCRIPTION
update user group


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for update


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-usergroup(1)\fP