.nh
.TH "HARBOR" "1" "Mar 2025" "Habor Community" "Harbor User Mannuals"

.SH NAME
harbor-tag-retention-list - List tag retention rules of a project


.SH SYNOPSIS
\fBharbor tag retention list [flags]\fP


.SH DESCRIPTION
Retrieve and display the tag retention rules for a specific project in Harbor.

.PP
Tag retention rules define policies for automatically keeping or deleting image tags
within a project. Using this command, you can view the currently configured
retention rules.

.PP
Usage:
  - Specify the project \fBeither by name or by ID\fP, but not both.
  - If neither is provided, you will be prompted to select a project.
  - The rules will be displayed in a formatted output.

.PP
Examples:
  # List retention rules using project name
  harbor tag retention list --project-name my-project

.PP
# List retention rules using project ID
  harbor tag retention list --project-id 42

.PP
# List retention rules in JSON format
  harbor tag retention list --project-name my-project --output-format json


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB-i\fP, \fB--project-id\fP=-1
	Project ID

.PP
\fB-p\fP, \fB--project-name\fP=""
	Project name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-tag-retention(1)\fP


.SH HISTORY
30-Mar-2025 Auto generated by spf13/cobra
