.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-ldap - Manage ldap users and groups


.SH SYNOPSIS
\fBharbor ldap [flags]\fP


.SH DESCRIPTION
Manage ldap users and groups


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for ldap


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  harbor ldap ping
.EE


.SH SEE ALSO
\fBharbor(1)\fP, \fBharbor-ldap-import(1)\fP, \fBharbor-ldap-ping(1)\fP, \fBharbor-ldap-search(1)\fP