.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-project-delete - Delete project by name or ID


.SH SYNOPSIS
\fBharbor project delete [flags]\fP


.SH DESCRIPTION
Delete project by name or ID. Multiple projects can be deleted by providing their names as arguments. If no arguments are provided, it will prompt for the project name. Use --project-id to specify the project ID for single project directly. The --force flag will delete all repositories and artifacts within the project.


.SH OPTIONS
\fB--force\fP[=false]
	Forcefully delete all repositories, artifacts, and policies in the project. Use with extreme caution—this action is irreversible.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for delete

.PP
\fB--project-id\fP=""
	Specify project ID instead of project name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
harbor project delete [projectname1] [projectname2] or harbor project delete --project-id [projectid]
.EE


.SH SEE ALSO
\fBharbor-project(1)\fP