.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-scanner-delete - Delete a scanner registration


.SH SYNOPSIS
\fBharbor scanner delete [scanner-name] [flags]\fP


.SH DESCRIPTION
Delete a scanner registration from Harbor.

.PP
You can:
  - Provide the scanner name as an argument to delete it directly, or
  - Omit the argument to select a scanner interactively.

.PP
Note: Deleting a scanner will permanently remove its registration and associated metadata from the system.

.PP
Examples:
  # Delete a scanner by name
  harbor scanner delete trivy-scanner

.PP
# Interactively choose a scanner to delete
  harbor scanner delete


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-scanner(1)\fP