.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-tag-retention-list - display retention policy for a project


.SH SYNOPSIS
\fBharbor tag retention list [PROJECT_NAME] [flags]\fP


.SH DESCRIPTION
retrieve and display retention policy configured for a project


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--retention-id\fP=0
	retention policy ID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-tag-retention(1)\fP