.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-replication-policies-delete - delete replication policy by name or id


.SH SYNOPSIS
\fBharbor replication policies delete [NAME|ID] [flags]\fP


.SH DESCRIPTION
delete replication policy by name or id


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-replication-policies(1)\fP