.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-jobservice-schedules - Manage schedules (list/status/pause-all/resume-all)


.SH SYNOPSIS
\fBharbor jobservice schedules [flags]\fP


.SH DESCRIPTION
List schedules and manage global scheduler status.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for schedules


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-jobservice(1)\fP, \fBharbor-jobservice-schedules-list(1)\fP, \fBharbor-jobservice-schedules-pause-all(1)\fP, \fBharbor-jobservice-schedules-resume-all(1)\fP, \fBharbor-jobservice-schedules-status(1)\fP