.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-jobservice-schedules-list - List schedules (supports --page and --page-size)


.SH SYNOPSIS
\fBharbor jobservice schedules list [flags]\fP


.SH DESCRIPTION
Display all job schedules with pagination support.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--page\fP=1
	Page number

.PP
\fB--page-size\fP=20
	Number of items per page


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
harbor jobservice schedules list --page 1 --page-size 20
.EE


.SH SEE ALSO
\fBharbor-jobservice-schedules(1)\fP