.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-jobservice-queues-list - List all job queues


.SH SYNOPSIS
\fBharbor jobservice queues list [flags]\fP


.SH DESCRIPTION
Display all job queues with their pending job counts and latency.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
harbor jobservice queues list
.EE


.SH SEE ALSO
\fBharbor-jobservice-queues(1)\fP