.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-gc-list - List GC history


.SH SYNOPSIS
\fBharbor gc list [flags]\fP


.SH DESCRIPTION
List GC (Garbage Collection) history in Harbor.

.PP
This command displays a list of GC executions with their status, creation time,
and other details. You can control the output using pagination flags and format options.

.PP
Examples:
  # List GC history with default pagination (page 1, 10 items per page)
  harbor gc list

.PP
# List GC history with custom pagination
  harbor gc list --page 2 --page-size 20

.PP
# List GC history with sorting by creation time (newest first)
  harbor gc list --sort -creation_time

.PP
# Filter GC history by status
  harbor gc list -q status=Success


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB-p\fP, \fB--page\fP=1
	Page number

.PP
\fB-s\fP, \fB--page-size\fP=10
	Size of per page

.PP
\fB-q\fP, \fB--query\fP=""
	Query string to query resources

.PP
\fB--sort\fP=""
	Sort the resource list in ascending or descending order


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-gc(1)\fP