.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-replication-policies-list - List replication policies


.SH SYNOPSIS
\fBharbor replication policies list [flags]\fP


.SH DESCRIPTION
List replication policies


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--page\fP=1
	Page number

.PP
\fB--page-size\fP=0
	Size of per page (0 to fetch all)

.PP
\fB-q\fP, \fB--query\fP=""
	Query string to query resources

.PP
\fB--sort\fP=""
	Sort the resource list in ascending or descending order


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-replication-policies(1)\fP