.nh
.TH "HARBOR" "1"  "Habor Community" "Harbor User Mannuals"

.SH NAME
harbor-webhook-delete - Delete a webhook from a Harbor project


.SH SYNOPSIS
\fBharbor webhook delete [flags]\fP


.SH DESCRIPTION
This command deletes a webhook from the specified Harbor project.
You can either specify the project name and webhook ID directly using flags,
or interactively select a project and webhook if not provided.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete

.PP
\fB--project\fP=""
	Project Name

.PP
\fB--webhook\fP=""
	Webhook ID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  # Delete a webhook by specifying the project and webhook ID
  harbor-cli webhook delete --project my-project --webhook 5

  # Delete a webhook by selecting the project and webhook interactively
  harbor-cli webhook delete
.EE


.SH SEE ALSO
\fBharbor-webhook(1)\fP