.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-config-update - Set/update a specific config item


.SH SYNOPSIS
\fBharbor config update   [flags]\fP


.SH DESCRIPTION
Set/update the value of a specific CLI config item.
Case-insensitive field lookup, but uses the canonical (Go) field name internally.
If you specify --name, that credential (rather than the "current" one) will be updated.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for update

.PP
\fB-n\fP, \fB--name\fP=""
	Name of the credential to set fields on (default: the current credential)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX

  # Set/update the current credential's password
  harbor config update credentials.password myNewSecret

  # Set/update a credential's password by specifying the credential name
  harbor config update credentials.password myNewSecret --name admin@http://demo.goharbor.io

.EE


.SH SEE ALSO
\fBharbor-config(1)\fP