.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-config-delete - Delete (clear) a specific config item


.SH SYNOPSIS
\fBharbor config delete  [flags]\fP


.SH DESCRIPTION
Clear the value of a specific CLI config item by setting it to its zero value.
Case-insensitive field lookup, but uses the canonical (Go) field name internally.
If you specify --name, that credential (rather than the "current" one) will be used.


.SH OPTIONS
\fB--current\fP[=false]
	Remove current credentials from the config

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for delete

.PP
\fB-n\fP, \fB--name\fP=""
	Name of the credential to delete fields from (default: the current credential)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX

  # Clear the current credential's password
  harbor config delete credentials.password

  # Clear a specific credential's password using --name
  harbor config delete credentials.password --name admin@http://demo.goharbor.io

  # Clear the current credential
  harbor config delete --current

.EE


.SH SEE ALSO
\fBharbor-config(1)\fP