.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-scanner - scanner commands


.SH SYNOPSIS
\fBharbor scanner [flags]\fP


.SH DESCRIPTION
scanner commands


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for scanner


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor(1)\fP, \fBharbor-scanner-create(1)\fP, \fBharbor-scanner-delete(1)\fP, \fBharbor-scanner-list(1)\fP, \fBharbor-scanner-metadata(1)\fP, \fBharbor-scanner-set-default(1)\fP, \fBharbor-scanner-update(1)\fP, \fBharbor-scanner-view(1)\fP