.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-user-create - create user


.SH SYNOPSIS
\fBharbor user create [flags]\fP


.SH DESCRIPTION
create user


.SH OPTIONS
\fB--comment\fP=""
	Comment (optional)

.PP
\fB--email\fP=""
	Email

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--password\fP=""
	Password

.PP
\fB--realname\fP=""
	Realname

.PP
\fB--username\fP=""
	Username


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-user(1)\fP