.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-user-password - Reset user password by name or id


.SH SYNOPSIS
\fBharbor user password [flags]\fP


.SH DESCRIPTION
Allows admin to reset the password for a specified user or select interactively if no username is provided.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for password


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-user(1)\fP