.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-quota-update - update quotas for projects


.SH SYNOPSIS
\fBharbor quota update [QuotaID] [flags]\fP


.SH DESCRIPTION
update quotas for projects


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for update

.PP
\fB--project-id\fP=""
	Get quota by project ID

.PP
\fB--project-name\fP=""
	Get quota by project-name

.PP
\fB--storage\fP=""
	Enter storage size (e.g., 50GiB, 20MiB, 4TiB)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-quota(1)\fP