.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-config-get - Get Harbor configurations


.SH SYNOPSIS
\fBharbor config get [flags]\fP


.SH DESCRIPTION
Get Harbor system configurations.

.EX
	This command retrieves the current configurations from Harbor and stores them in your local config file.
.EE


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-config(1)\fP