.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-login - Log in to Harbor registry


.SH SYNOPSIS
\fBharbor login [server] [flags]\fP


.SH DESCRIPTION
Authenticate with Harbor Registry.


.SH OPTIONS
\fB-n\fP, \fB--context-name\fP=""
	Login context name (optional)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for login

.PP
\fB-p\fP, \fB--password\fP=""
	Password

.PP
\fB--password-stdin\fP[=false]
	Take the password from stdin

.PP
\fB--skip-verify-client\fP[=false]
	Skip whether the clients basic auth credentials shall be validated against the Harbor server during login. This is not recommended as it may lead to storing invalid credentials. Use this flag if you want to skip validation of credentials during login, for example, when the Harbor server is not reachable at the moment of login but you still want to store the credentials for later use.

.PP
\fB-u\fP, \fB--username\fP=""
	Username


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor(1)\fP