.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-gc-update-schedule - update-schedule [schedule-type: none|hourly|daily|weekly|custom]


.SH SYNOPSIS
\fBharbor gc update-schedule [flags]\fP


.SH DESCRIPTION
Configure or update the automatic GC schedule.

.PP
Available schedule types:
  - none:    Disable automatic GC
  - hourly:  Run GC every hour
  - daily:   Run GC once per day
  - weekly:  Run GC once per week
  - custom:  Define a custom schedule using a cron expression


.SH OPTIONS
\fB--cron\fP=""
	Cron expression for custom schedule (include the expression in double quotes)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update-schedule


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-gc(1)\fP