.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-scan-all-update-schedule - update-schedule [schedule-type: none|hourly|daily|weekly|custom]


.SH SYNOPSIS
\fBharbor scan-all update-schedule [flags]\fP


.SH DESCRIPTION
update-schedule [schedule-type: none|hourly|daily|weekly|custom]


.SH OPTIONS
\fB--cron\fP=""
	Cron expression (include the expression in double quotes)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update-schedule


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-scan-all(1)\fP