.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-project-member-view - get project member information


.SH SYNOPSIS
\fBharbor project member view [projectName] [memberID] [flags]\fP


.SH DESCRIPTION
get project member information


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for view

.PP
\fB--id\fP[=false]
	parses projectName as an ID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  harbor project member view my-project 5
  harbor project member view my-project 5 --wide
.EE


.SH SEE ALSO
\fBharbor-project-member(1)\fP