.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-config - Manage the config of the Harbor CLI


.SH SYNOPSIS
\fBharbor config [flags]\fP


.SH DESCRIPTION
The config command allows you to manage configurations of the Harbor CLI.
				You can add, get, or delete specific config item, as well as list all config items of the Harbor Cli


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for config


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor(1)\fP, \fBharbor-config-delete(1)\fP, \fBharbor-config-get(1)\fP, \fBharbor-config-list(1)\fP, \fBharbor-config-update(1)\fP