.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-jobservice-queues - Manage job queues (list, stop, pause, resume)


.SH SYNOPSIS
\fBharbor jobservice queues [flags]\fP


.SH DESCRIPTION
List job queues and perform actions on them (stop/pause/resume).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for queues


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-jobservice(1)\fP, \fBharbor-jobservice-queues-list(1)\fP, \fBharbor-jobservice-queues-pause(1)\fP, \fBharbor-jobservice-queues-resume(1)\fP, \fBharbor-jobservice-queues-stop(1)\fP