.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-tag-immutable-list - Display all immutable tag rules for a project


.SH SYNOPSIS
\fBharbor tag immutable list [PROJECT_NAME] [flags]\fP


.SH DESCRIPTION
Retrieve and display a list of immutable tag rules configured for a specified project in Harbor.
Immutable tag rules prevent specific tags from being deleted or overwritten, ensuring better security and compliance.
You can specify the project name as an argument or, if omitted, you will be prompted to select one interactively.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  
  # List immutable tag rules for a specific project  
  harbor tag immutable list my-project  

  # List immutable tag rules interactively (if no project name is provided)  
  harbor tag immutable list  
  
.EE


.SH SEE ALSO
\fBharbor-tag-immutable(1)\fP