.nh
.TH "HARBOR" "1" "Apr 2025" "Habor Community" "Harbor User Mannuals"

.SH NAME
harbor-tag-immutable-create - create immutable tag rule


.SH SYNOPSIS
\fBharbor tag immutable create [flags]\fP


.SH DESCRIPTION
create immutable tag rule to the project in harbor


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--repo-decoration\fP=""
	repository which either apply or exclude from the rule

.PP
\fB--repo-list\fP=""
	list of repository to which to either apply or exclude from the rule

.PP
\fB--tag-decoration\fP=""
	tags which either apply or exclude from the rule

.PP
\fB--tag-list\fP=""
	list of tags to which to either apply or exclude from the rule


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
harbor tag immutable create
.EE


.SH SEE ALSO
\fBharbor-tag-immutable(1)\fP