.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-tag-retention-tasks - Manage retention execution tasks


.SH SYNOPSIS
\fBharbor tag retention tasks [flags]\fP


.SH DESCRIPTION
List retention execution tasks


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for tasks


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBharbor-tag-retention(1)\fP, \fBharbor-tag-retention-tasks-list(1)\fP