.nh
.TH "HARBOR" "1"  "Harbor Community" "Harbor User Manuals"

.SH NAME
harbor-instance-ping - Ping preheat provider instance by name or id


.SH SYNOPSIS
\fBharbor instance ping [NAME|ID] [flags]\fP


.SH DESCRIPTION
Ping a preheat provider instance to test its connectivity in Harbor. You can specify the instance
by name or ID directly as an argument. If no argument is provided, you will be prompted to select
an instance from a list of available instances.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for ping

.PP
\fB--id\fP[=false]
	Get instance by id


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP=""
	config file (default is $HOME/.config/harbor-cli/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml|csv

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  harbor-cli instance ping my-instance
  harbor-cli instance ping 1 --id
.EE


.SH SEE ALSO
\fBharbor-instance(1)\fP