version: 2
project_name: harbor

before:
  hooks:
    - go mod tidy

builds:
- main: ./cmd/harbor/main.go
  env:
    - CGO_ENABLED=0
  ldflags:
    - -w -s -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.GitCommit={{.FullCommit}}
    - -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.Version={{.Tag}}
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
  mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  -
    homepage: https://github.com/goharbor/harbor-cli/
    maintainer: Harbor Community
    description: |-
      CLI for Harbor Container Registry
    formats:
      - rpm
      - deb
      - apk
      - archlinux

sboms:
  - artifacts: archive

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  name_template: "HarborCLI {{.Tag}}"
  draft: true                 # Set to false to ensure that releases are published, not kept as drafts
  prerelease: auto            # Auto-detect prereleases based on tag
  replace_existing_draft: true
  replace_existing_artifacts: true
  disable: false              # Ensure release publishing is enabled
  github:
    owner: goharbor           # Your GitHub repository owner
    name: harbor-cli          # Your GitHub repository name

# https://goreleaser.com/customization/homebrew/
brews:
  - repository:
      owner: goharbor
      name: homebrew-tap
    name: harbor-cli
    commit_author:
      name: harbor-bot
      email: noreply@goharbor.io
    url_template: "https://{{ .Env.ARTEFACTS_FQDN }}/harbor-cli/releases/{{ .Version }}/{{ .ArtifactName }}"
    homepage: "https://goharbor.io"
    description: "harbor is an integrated platform to orchestrate the delivery of applications"
    test: |
      system "#{bin}/harbor-cli version"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "merge conflict"
  groups:
    - title: "Dependency updates"
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: "Other work"
      order: 9999
