.nh
.TH "HARBOR" "1" "Jul 2024" "Habor Community" "Harbor User Mannuals"

.SH NAME
.PP
harbor-project-create - create project


.SH SYNOPSIS
.PP
\fBharbor project create [flags]\fP


.SH DESCRIPTION
.PP
create project


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--name\fP=""
	Name of the project

.PP
\fB--proxy-cache\fP[=false]
	Whether the project is a proxy cache project

.PP
\fB--public\fP[=false]
	Project is public or private. Private by default

.PP
\fB--registry-id\fP=""
	ID of referenced registry when creating the proxy cache project

.PP
\fB--storage-limit\fP="-1"
	Storage quota of the project


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP="/home/bupd/.harbor/config.yaml"
	config file (default is $HOME/.harbor/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
.PP
\fBharbor-project(1)\fP
