.nh
.TH "HARBOR" "1" "Jul 2024" "Habor Community" "Harbor User Mannuals"

.SH NAME
.PP
harbor-artifact-delete - delete an artifact


.SH SYNOPSIS
.PP
\fBharbor artifact delete [flags]\fP


.SH DESCRIPTION
.PP
delete an artifact


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP="/home/bupd/.harbor/config.yaml"
	config file (default is $HOME/.harbor/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
.PP
\fBharbor-artifact(1)\fP
