.nh
.TH "HARBOR" "1" "Jul 2024" "Habor Community" "Harbor User Mannuals"

.SH NAME
.PP
harbor-login - Log in to Harbor registry


.SH SYNOPSIS
.PP
\fBharbor login [server] [flags]\fP


.SH DESCRIPTION
.PP
Authenticate with Harbor Registry.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for login

.PP
\fB--name\fP=""
	name for the set of credentials

.PP
\fB-p\fP, \fB--password\fP=""
	Password

.PP
\fB-u\fP, \fB--username\fP=""
	Username


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP="/home/bupd/.harbor/config.yaml"
	config file (default is $HOME/.harbor/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
.PP
\fBharbor(1)\fP
