.nh
.TH "HARBOR" "1" "Jul 2024" "Habor Community" "Harbor User Mannuals"

.SH NAME
.PP
harbor-registry - Manage registries


.SH SYNOPSIS
.PP
\fBharbor registry [flags]\fP


.SH DESCRIPTION
.PP
Manage registries in Harbor


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for registry


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP="/home/bupd/.harbor/config.yaml"
	config file (default is $HOME/.harbor/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  harbor registry list
.EE


.SH SEE ALSO
.PP
\fBharbor(1)\fP, \fBharbor-registry-create(1)\fP, \fBharbor-registry-delete(1)\fP, \fBharbor-registry-info(1)\fP, \fBharbor-registry-list(1)\fP, \fBharbor-registry-update(1)\fP, \fBharbor-registry-view(1)\fP
