.nh
.TH "HARBOR" "1" "Jul 2024" "Habor Community" "Harbor User Mannuals"

.SH NAME
.PP
harbor-artifact-scan-stop - Stop a scan of an artifact


.SH SYNOPSIS
.PP
\fBharbor artifact scan stop [flags]\fP


.SH DESCRIPTION
.PP
Stop a scan of an artifact in Harbor Repository


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for stop


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP="/home/bupd/.harbor/config.yaml"
	config file (default is $HOME/.harbor/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
harbor artifact scan stop <project>/<repository>/<reference>
.EE


.SH SEE ALSO
.PP
\fBharbor-artifact-scan(1)\fP
