.nh
.TH "HARBOR" "1" "Jul 2024" "Habor Community" "Harbor User Mannuals"

.SH NAME
.PP
harbor-project - Manage projects and assign resources to them


.SH SYNOPSIS
.PP
\fBharbor project [flags]\fP


.SH DESCRIPTION
.PP
Manage projects in Harbor


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for project


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP="/home/bupd/.harbor/config.yaml"
	config file (default is $HOME/.harbor/config.yaml)

.PP
\fB-o\fP, \fB--output-format\fP=""
	Output format. One of: json|yaml

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH EXAMPLE
.EX
  harbor project list
.EE


.SH SEE ALSO
.PP
\fBharbor(1)\fP, \fBharbor-project-create(1)\fP, \fBharbor-project-delete(1)\fP, \fBharbor-project-list(1)\fP, \fBharbor-project-logs(1)\fP, \fBharbor-project-view(1)\fP
