name: ci-pipeline-robot
description: "Robot account for CI/CD pipeline"
duration: 90
level: system 
permissions:
  - access: 
    - resource: repository
      actions:
        - pull
        - push
    - resources:
        - artifact
        - scan
      actions:
        - read
    kind: project
    namespace: demo
  - access:
    - resources: ["*"]
      actions: ["*"]
    kind: system
    namespace: /
